# Dependencies
markdown:            kramdown

# Setup
title:            Let's open source!
tagline:          'Blog pour un amateur du system embarqué.'
description:      'Ayant été une physicienne pendant plus que 10 ans. Maintenant je me transforme en un ingénieur system embarqué.'
url:              http://wantingchen.github.io

author:
  name:           Wan-Ting CHEN
  url:            http://wantingchen.github.io
  github :        wantingchen
  email:          wanting@gmail.com
  introduction:   'Ayant été une physicienne pendant plus que 10 ans. Maintenant je me transforme en un ingénieur system embarqué.'

#PAGINATION
paginate:         5
paginate_path: "/blog/page:num/"

# Custom vars
#version:          1.0.0

timezone: Europe/Paris

kramdown:
  auto_ids:       true
  footnote_nr:    1   
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true

comments :
  provider : disqus
  disqus:
    short_name : gnitnaw

analytics :
  provider : google 
  google : 
    tracking_id : 'UA-75609833-2'

gems: [jekyll-paginate, jekyll-gist, jekyll-last-modified-at]

excerpt_separator: "<!-- more -->"

github_username:	wantingchen
linkedin_username:	wan-ting-chen-30128b5b
